-- Additive security bootstrap required by middleware and /api/security/ip-check.
-- Safe to rerun: it does not update or delete existing application rows.
begin;

create table if not exists public.site_security_settings (
  id bigint primary key,
  lockdown_enabled boolean not null default false,
  lockdown_message text,
  lockdown_password text,
  maintenance_mode boolean not null default false,
  force_logout_epoch bigint not null default 0,
  lockdown_version integer not null default 1,
  emergency_banner_enabled boolean not null default false,
  emergency_banner_text text,
  emergency_banner_level text not null default 'info',
  updated_at timestamptz not null default now()
);
alter table public.site_security_settings add column if not exists maintenance_mode boolean not null default false;
insert into public.site_security_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.ip_bans (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  reason text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);
create unique index if not exists ip_bans_ip_address_idx on public.ip_bans (ip_address);

create table if not exists public.user_bans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists user_bans_active_user_idx on public.user_bans (user_id) where active;

alter table public.site_security_settings enable row level security;
alter table public.ip_bans enable row level security;
alter table public.user_bans enable row level security;

revoke all on public.site_security_settings, public.ip_bans, public.user_bans from anon, authenticated;

create or replace function public.get_ip_ban_detail(ip text)
returns table (banned boolean, reason text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.ip_bans b where b.ip_address::text = ip
  ), (
    select b.reason from public.ip_bans b
    where b.ip_address::text = ip order by b.created_at desc, b.id desc limit 1
  )
$$;
revoke all on function public.get_ip_ban_detail(text) from public;
grant execute on function public.get_ip_ban_detail(text) to anon, authenticated, service_role;

commit;
