"use client";
import { FormEvent, useEffect, useState } from "react";
import { AccessDeniedCard } from "@/components/AccessDeniedCard";
import { useMeAccess } from "@/lib/hooks/useMeAccess";

type Config={enabled:boolean;fromName:string;fromEmail:string;replyTo:string;staffNotificationEmail:string;sendCustomerMessages:boolean;sendStatusUpdates:boolean;sendPaymentUpdates:boolean};
type Template={key:string;name:string;subject:string;heading:string;body:string;button_label:string;is_enabled:boolean};
const input="ui-input w-full";
export default function StaffEmailPage(){
 const {data:access,isLoading}=useMeAccess(); const allowed=(access?.permissions??[]).includes("emails.manage");
 const [config,setConfig]=useState<Config|null>(null),[templates,setTemplates]=useState<Template[]>([]),[provider,setProvider]=useState(false),[message,setMessage]=useState(""),[testTo,setTestTo]=useState("");
 useEffect(()=>{if(!allowed)return;void fetch("/api/staff/emails").then(r=>r.json()).then(j=>{if(j.error)setMessage(j.error);else{setConfig(j.config);setTemplates(j.templates);setProvider(j.providerConfigured)}})},[allowed]);
 if(isLoading)return <div className="ui-card">Loading…</div>; if(!allowed)return <AccessDeniedCard message="You do not have access to email settings."/>; if(!config)return <div className="ui-card">{message||"Loading email settings…"}</div>;
 const save=async(e:FormEvent)=>{e.preventDefault();setMessage("Saving…");const r=await fetch("/api/staff/emails",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({config,templates})});const j=await r.json();setMessage(j.error||"Email settings saved.")};
 const test=async()=>{setMessage("Sending test…");const r=await fetch("/api/staff/emails/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:testTo})});const j=await r.json();setMessage(j.error||(j.sent?"Test email sent.":"Test email was not sent."))};
 return <main><p className="text-xs uppercase tracking-[.2em] text-brand-accent">Commerce</p><h1 className="mt-1 text-3xl font-semibold">Email center</h1><p className="mt-2 text-sm text-brand-textMuted">Control transactional order email without editing code. Available variables: {"{{customer_name}}, {{product_name}}, {{order_label}}, {{status}}, {{price}}"}.</p>
 {!provider?<div className="mt-5 rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">RESEND_API_KEY is not configured in Vercel. Settings can be prepared, but mail will not send yet.</div>:null}
 <form onSubmit={save} className="mt-6 space-y-6"><section className="ui-card"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Delivery</h2><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/> Enable email</label></div><div className="mt-4 grid gap-4 md:grid-cols-2">{[["Sender name","fromName"],["Sender email","fromEmail"],["Reply-to email","replyTo"],["Staff notification email","staffNotificationEmail"]].map(([label,key])=><label key={key} className="text-sm"><span className="mb-1 block text-brand-textMuted">{label}</span><input className={input} value={String(config[key as keyof Config]??"")} onChange={e=>setConfig({...config,[key]:e.target.value})}/></label>)}</div><div className="mt-4 flex flex-wrap gap-5 text-sm">{[["Customer messages","sendCustomerMessages"],["Status updates","sendStatusUpdates"],["Payment updates","sendPaymentUpdates"]].map(([label,key])=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={Boolean(config[key as keyof Config])} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>{label}</label>)}</div></section>
 <section className="space-y-4"><h2 className="text-xl font-semibold">Templates</h2>{templates.map((t,index)=><details key={t.key} className="ui-card" open={index===0}><summary className="cursor-pointer font-semibold">{t.name}<span className="ml-2 text-xs text-brand-textMuted">{t.key}</span></summary><div className="mt-4 space-y-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={t.is_enabled} onChange={e=>setTemplates(v=>v.map(x=>x.key===t.key?{...x,is_enabled:e.target.checked}:x))}/> Enable this email</label>{[["Subject","subject"],["Heading","heading"],["Button label","button_label"]].map(([label,key])=><label key={key} className="block text-sm"><span className="mb-1 block text-brand-textMuted">{label}</span><input className={input} value={String(t[key as keyof Template])} onChange={e=>setTemplates(v=>v.map(x=>x.key===t.key?{...x,[key]:e.target.value}:x))}/></label>)}<label className="block text-sm"><span className="mb-1 block text-brand-textMuted">Body</span><textarea className={`${input} min-h-28`} value={t.body} onChange={e=>setTemplates(v=>v.map(x=>x.key===t.key?{...x,body:e.target.value}:x))}/></label></div></details>)}</section>
 <div className="flex flex-wrap items-end gap-3"><button className="ui-btn ui-btn-primary" type="submit">Save email settings</button><label className="text-sm"><span className="mb-1 block text-brand-textMuted">Send test to</span><input className={input} type="email" value={testTo} onChange={e=>setTestTo(e.target.value)} placeholder="you@example.com"/></label><button className="ui-btn ui-btn-secondary" type="button" onClick={test}>Send test</button></div>{message?<p className="text-sm text-brand-textMuted">{message}</p>:null}</form></main>
}
