"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {supabaseBrowser} from "@/lib/supabaseClient";
import {useMeAccess} from "@/lib/hooks/useMeAccess";
import {AccessDeniedCard} from "@/components/AccessDeniedCard";

type Order={id:string;order_number:string|null;customer_id:string;product_name:string;status:string;quantity:number;specifications:Record<string,string|null>;customer_notes:string|null;staff_notes:string|null;agreed_price_cents:number|null;payment_status:string;amount_paid_cents:number;target_date:string|null};
type Message={id:number;sender_id:string;body:string;is_internal:boolean;created_at:string};
const statuses=["requested","needs_information","accepted","awaiting_payment","in_progress","customer_review","ready","completed","declined","cancelled"];
const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function StaffOrderDetail(){
 const {id}=useParams<{id:string}>();const supabase=useMemo(()=>supabaseBrowser(),[]);const {data:access,isLoading}=useMeAccess();const perms=new Set(access?.permissions??[]);const canView=perms.has("orders.view")||perms.has("orders.manage");const canManage=perms.has("orders.manage");
 const [order,setOrder]=useState<Order|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [userId,setUserId]=useState("");const [body,setBody]=useState("");const [internal,setInternal]=useState(false);const [price,setPrice]=useState("");const [paid,setPaid]=useState("");const [target,setTarget]=useState("");const [staffNotes,setStaffNotes]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{const auth=await supabase.auth.getUser();setUserId(auth.data.user?.id??"");const[o,m]=await Promise.all([supabase.from("orders").select("*").eq("id",id).maybeSingle(),supabase.from("order_messages").select("*").eq("order_id",id).order("created_at")]);const row=o.data as Order|null;setOrder(row);setMessages((m.data??[])as Message[]);if(row){setPrice(row.agreed_price_cents==null?"":String(row.agreed_price_cents/100));setPaid(String(row.amount_paid_cents/100));setTarget(row.target_date??"");setStaffNotes(row.staff_notes??"")}setError(o.error?.message??m.error?.message??"")},[id,supabase]);
 useEffect(()=>{if(!canView)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[canView,load]);
 async function updateStatus(status:string){if(!order)return;const from=order.status;const r=await supabase.from("orders").update({status}).eq("id",id);if(r.error){setError(r.error.message);return}await supabase.from("order_status_history").insert({order_id:id,from_status:from,to_status:status,changed_by:userId});await load()}
 async function save(){const priceCents=price.trim()?Math.round(Number(price)*100):null;const paidCents=paid.trim()?Math.round(Number(paid)*100):0;const payment_status=priceCents==null?"not_required":paidCents<=0?"unpaid":paidCents>=priceCents?"paid":"partial";const r=await supabase.from("orders").update({agreed_price_cents:priceCents,amount_paid_cents:paidCents,payment_status,target_date:target||null,staff_notes:staffNotes||null}).eq("id",id);if(r.error)setError(r.error.message);else await load()}
 async function send(e:FormEvent){e.preventDefault();const r=await supabase.from("order_messages").insert({order_id:id,sender_id:userId,body:body.trim(),is_internal:internal});if(r.error)setError(r.error.message);else{setBody("");await load()}}
 if(isLoading)return <div className="ui-card">Loading…</div>;if(!canView)return <AccessDeniedCard message="You do not have access to orders."/>;if(!order)return <p className="text-rose-200">{error||"Order not found."}</p>;const input="rounded-xl border border-zinc-700 bg-black/40 px-3 py-2 outline-none focus:border-brand-primary";
 return <main><p className="text-xs uppercase tracking-[.2em] text-brand-primary">{order.order_number||"Request pending"}</p><h1 className="mt-1 text-3xl font-semibold">{order.product_name}</h1><p className="mt-1 text-sm text-brand-textMuted">Customer {order.customer_id} · Quantity {order.quantity}</p>
 <div className="mt-5 flex flex-wrap gap-2">{statuses.map(s=><button disabled={!canManage} onClick={()=>void updateStatus(s)} key={s} className={`rounded-full border px-3 py-1.5 text-xs ${order.status===s?"border-brand-primary bg-brand-primary/10 text-brand-primary":"border-zinc-700 text-brand-textMuted"}`}>{pretty(s)}</button>)}</div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-zinc-800 bg-black/30 p-5"><h2 className="font-semibold">Order details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Agreed price ($)<input disabled={!canManage} className={`${input} mt-1 w-full`} type="number" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="text-sm">Amount paid ($)<input disabled={!canManage} className={`${input} mt-1 w-full`} type="number" step=".01" value={paid} onChange={e=>setPaid(e.target.value)}/></label><label className="text-sm">Target date<input disabled={!canManage} className={`${input} mt-1 w-full`} type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="text-sm sm:col-span-2">Internal notes<textarea disabled={!canManage} className={`${input} mt-1 min-h-24 w-full`} value={staffNotes} onChange={e=>setStaffNotes(e.target.value)}/></label></div>{canManage?<button onClick={()=>void save()} className="mt-3 rounded-xl bg-brand-primary px-4 py-2 font-semibold text-black">Save details</button>:null}<div className="mt-5 border-t border-zinc-800 pt-4 text-sm"><div className="text-brand-textMuted">Customer notes</div><p className="mt-1 whitespace-pre-wrap">{order.customer_notes||"None"}</p></div></section>
 <section><h2 className="font-semibold">Conversation</h2><div className="mt-3 max-h-[480px] space-y-3 overflow-y-auto">{messages.map(m=><div key={m.id} className={`rounded-xl border p-3 text-sm ${m.is_internal?"border-sky-500/40 bg-sky-500/10":"border-zinc-800 bg-black/30"}`}><div className="text-[10px] text-brand-textMuted">{m.is_internal?"INTERNAL NOTE":m.sender_id===order.customer_id?"CUSTOMER":"KEYMOURA"} · {new Date(m.created_at).toLocaleString()}</div><p className="mt-1 whitespace-pre-wrap">{m.body}</p></div>)}</div>{canManage?<form onSubmit={send} className="mt-3"><textarea required className={`${input} min-h-24 w-full`} value={body} onChange={e=>setBody(e.target.value)} placeholder="Reply to customer or add an internal note…"/><label className="mt-2 flex items-center gap-2 text-xs text-brand-textMuted"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal note (customer cannot see)</label><button className="mt-3 rounded-xl bg-brand-primary px-4 py-2 font-semibold text-black">Send</button></form>:null}</section></div>{error?<p className="mt-4 text-rose-200">{error}</p>:null}</main>
}
