import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "CNC Capabilities & Materials", description: "Materials, project types, and practical limits for KeyMoura custom CNC work." };

export default function CapabilitiesPage() {
  const materials = [["Plastics", "Delrin/acetal, HDPE, acrylic, and other machinable plastics."], ["Wood", "Hardwoods, softwoods, plywood, and selected engineered sheet goods."], ["Aluminum", "Machinable aluminum projects reviewed individually for geometry, finish, and tolerance."], ["Other materials", "Ask first. Workholding, tooling, dust, heat, and safety determine what is practical."]];
  return <main className="mx-auto max-w-6xl px-4 py-12 sm:py-16"><p className="text-xs font-semibold uppercase tracking-[.22em] text-brand-primary">Capabilities</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight sm:text-5xl">A practical path from design to machined part.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-brand-textMuted">KeyMoura focuses on custom routing and light machining for one-off parts, prototypes, signs, fixtures, plates, knobs, trim pieces, and short runs. Every request is reviewed before a capability or delivery promise is made.</p>
    <section className="mt-12"><h2 className="text-2xl font-semibold">Supported materials</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{materials.map(([title, body]) => <article key={title} className="rounded-2xl border border-zinc-800 bg-black/30 p-6"><h3 className="font-semibold text-brand-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-brand-textMuted">{body}</p></article>)}</div></section>
    <section className="mt-12 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-zinc-800 bg-black/30 p-6"><h2 className="text-xl font-semibold">Helpful project information</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-6 text-brand-textMuted"><li>Overall dimensions and critical features</li><li>Material and finish preference</li><li>Quantity and target date</li><li>How the part will be used</li><li>CAD, drawing, sketch, or reference photos</li></ul></article><article className="rounded-2xl border border-zinc-800 bg-black/30 p-6"><h2 className="text-xl font-semibold">Reviewed case by case</h2><p className="mt-4 text-sm leading-6 text-brand-textMuted">Deep pockets, very thin walls, complex undercuts, unknown alloys, safety-critical uses, large stock, exceptionally tight tolerances, and specialty finishes may require a revised design, outside service, or a declined request.</p></article></section>
    <div className="mt-10 flex flex-wrap gap-3"><Link href="/design-guide" className="catalog-action-secondary rounded-full px-5 py-2.5 font-medium">Read the design guide</Link><Link href="/orders/new" className="catalog-action-primary rounded-full px-5 py-2.5 font-semibold">Request custom work</Link></div>
  </main>;
}
