begin;

create sequence if not exists public.keymoura_order_number_seq start 1;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  short_description text,
  description text,
  image_url text,
  category text,
  starting_price_cents integer check (starting_price_cents is null or starting_price_cents >= 0),
  is_custom boolean not null default true,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique,
  customer_id uuid not null references auth.users(id) on delete restrict,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  status text not null default 'requested' check (status in (
    'requested','needs_information','accepted','awaiting_payment','in_progress',
    'customer_review','ready','completed','declined','cancelled'
  )),
  quantity integer not null default 1 check (quantity between 1 and 1000),
  specifications jsonb not null default '{}'::jsonb,
  customer_notes text,
  staff_notes text,
  agreed_price_cents integer check (agreed_price_cents is null or agreed_price_cents >= 0),
  payment_status text not null default 'not_required' check (payment_status in ('not_required','unpaid','partial','paid','refunded')),
  amount_paid_cents integer not null default 0 check (amount_paid_cents >= 0),
  target_date date,
  accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_messages (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete restrict,
  body text not null check (char_length(btrim(body)) between 1 and 5000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists products_public_order_idx on public.products(is_published, sort_order, created_at desc);
create index if not exists orders_customer_idx on public.orders(customer_id, updated_at desc);
create index if not exists orders_status_idx on public.orders(status, updated_at desc);
create index if not exists order_messages_order_idx on public.order_messages(order_id, created_at);
create index if not exists order_history_order_idx on public.order_status_history(order_id, created_at);

create or replace function public.touch_commerce_updated_at()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products
for each row execute function public.touch_commerce_updated_at();
drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
for each row execute function public.touch_commerce_updated_at();

create or replace function public.assign_keymoura_order_number()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  if new.order_number is null and new.status not in ('requested','needs_information','declined') then
    new.order_number := 'KM-' || lpad(nextval('public.keymoura_order_number_seq')::text, 4, '0');
    new.accepted_at := coalesce(new.accepted_at, now());
  end if;
  if new.status = 'completed' then new.completed_at := coalesce(new.completed_at, now()); end if;
  return new;
end $$;

drop trigger if exists orders_assign_number on public.orders;
create trigger orders_assign_number before insert or update on public.orders
for each row execute function public.assign_keymoura_order_number();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_messages enable row level security;
alter table public.order_status_history enable row level security;

drop policy if exists "published products readable" on public.products;
create policy "published products readable" on public.products for select to anon, authenticated
using (is_published);
drop policy if exists "staff manage products" on public.products;
create policy "staff manage products" on public.products for all to authenticated
using ((select public.is_staff_user())) with check ((select public.is_staff_user()));

drop policy if exists "customers read own orders" on public.orders;
create policy "customers read own orders" on public.orders for select to authenticated
using ((select auth.uid()) = customer_id or (select public.is_staff_user()));
drop policy if exists "customers request orders" on public.orders;
create policy "customers request orders" on public.orders for insert to authenticated
with check ((select auth.uid()) = customer_id and status = 'requested' and order_number is null);
drop policy if exists "staff manage orders" on public.orders;
create policy "staff manage orders" on public.orders for all to authenticated
using ((select public.is_staff_user())) with check ((select public.is_staff_user()));

drop policy if exists "participants read order messages" on public.order_messages;
create policy "participants read order messages" on public.order_messages for select to authenticated
using (
  exists(select 1 from public.orders o where o.id=order_id and
    (o.customer_id=(select auth.uid()) or (select public.is_staff_user())))
  and (not is_internal or (select public.is_staff_user()))
);
drop policy if exists "participants send order messages" on public.order_messages;
create policy "participants send order messages" on public.order_messages for insert to authenticated
with check (
  sender_id=(select auth.uid()) and
  exists(select 1 from public.orders o where o.id=order_id and
    (o.customer_id=(select auth.uid()) or (select public.is_staff_user())))
  and (not is_internal or (select public.is_staff_user()))
);

drop policy if exists "participants read order history" on public.order_status_history;
create policy "participants read order history" on public.order_status_history for select to authenticated
using (exists(select 1 from public.orders o where o.id=order_id and
  (o.customer_id=(select auth.uid()) or (select public.is_staff_user()))));
drop policy if exists "staff add order history" on public.order_status_history;
create policy "staff add order history" on public.order_status_history for insert to authenticated
with check ((select public.is_staff_user()) and changed_by=(select auth.uid()));

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select, insert on public.orders to authenticated;
grant update, delete on public.orders to authenticated;
grant select, insert on public.order_messages to authenticated;
grant select, insert on public.order_status_history to authenticated;
grant usage, select on sequence public.keymoura_order_number_seq to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant select, insert, update, delete on public.products, public.orders, public.order_messages, public.order_status_history to service_role;

insert into public.permissions(key, name, description) values
 ('catalog.view','View catalog tools','View the staff product catalog'),
 ('catalog.manage','Manage catalog','Create, edit, publish, and archive products'),
 ('orders.view','View orders','View customer requests and orders'),
 ('orders.manage','Manage orders','Accept requests and manage orders')
on conflict(key) do update set name=excluded.name, description=excluded.description;

insert into public.role_permissions(role_key, permission_key)
select 'admin', key from (values ('catalog.view'),('catalog.manage'),('orders.view'),('orders.manage')) p(key)
on conflict do nothing;

notify pgrst, 'reload schema';
commit;
