"use client";

import { FormEvent, useMemo, useState } from "react";
import { OPTIONAL_MODULES, resolveModuleDependencies, type ModuleAvailability } from "@/lib/installer/model";

type Props = { initialState: { bootstrapReady: boolean; status: string; errorCode: string | null; modules: ModuleAvailability } };
type Stage = "unlock" | "system" | "site" | "modules" | "auth" | "owner" | "review" | "installing" | "success";
const stages: Stage[] = ["unlock","system","site","modules","auth","owner","review"];

export default function InstallerWizard({ initialState }: Props) {
  const [stage, setStage] = useState<Stage>("unlock");
  const [token, setToken] = useState(""); const [error, setError] = useState("");
  const [form, setForm] = useState({ siteName: "My Community", description: "", publicUrl: window.location.origin, logoUrl: "", primaryColor: "#dc2626", accentColor: "#f59e0b", forumTerm: "Community", knowledgeTerm: "Knowledge Base", vendorTerm: "Trusted Shop", modules: [] as string[], allowSignup: true, requireEmailConfirmation: true, email: "", password: "", username: "" });
  const selected = useMemo(() => resolveModuleDependencies(form.modules), [form.modules]);
  const step = stages.indexOf(stage); const progress = stage === "success" ? 100 : Math.max(5, ((step + 1) / stages.length) * 100);
  const update = (key: string, value: string | boolean | string[]) => setForm((old) => ({ ...old, [key]: value }));
  async function unlock(event: FormEvent) { event.preventDefault(); setError(""); const res = await fetch("/api/install/unlock", { method: "POST", headers: { Authorization: `Bearer ${token}` } }); setToken(""); if (!res.ok) return setError((await res.json()).error); setStage("system"); }
  async function install() { setStage("installing"); setError(""); const res = await fetch("/api/install/complete", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ siteName: form.siteName, description: form.description, publicUrl: form.publicUrl, logoUrl: form.logoUrl, primaryColor: form.primaryColor, accentColor: form.accentColor, terminology: { forum: form.forumTerm, knowledgeBase: form.knowledgeTerm, trustedVendor: form.vendorTerm }, modules: selected, auth: { allowSignup: form.allowSignup, requireEmailConfirmation: form.requireEmailConfirmation }, owner: { email: form.email, password: form.password, username: form.username } }) }); const body = await res.json(); if (!res.ok) { setError(body.error); return setStage("review"); } setStage("success"); }
  const next = () => setStage(stages[Math.min(stages.length - 1, step + 1)]); const back = () => setStage(stages[Math.max(0, step - 1)]);
  const toggleModule = (key: string) => {
    if (!initialState.modules[key as keyof ModuleAvailability]?.available) return;
    update("modules", form.modules.includes(key) ? form.modules.filter((x) => x !== key) : [...form.modules, key]);
  };

  return <main className="min-h-screen bg-zinc-950 px-4 py-10 text-zinc-100"><div className="mx-auto max-w-3xl overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900 shadow-2xl">
    <header className="border-b border-zinc-800 px-6 py-6"><p className="text-sm font-semibold uppercase tracking-[.2em] text-red-400">First-time setup</p><h1 className="mt-1 text-3xl font-bold">Community installer</h1><div className="mt-5 h-2 overflow-hidden rounded bg-zinc-800"><div className="h-full bg-red-600 transition-all" style={{ width: `${progress}%` }} /></div></header>
    <section className="space-y-5 p-6">
      {error && <div role="alert" className="rounded-lg border border-red-700 bg-red-950/60 p-4 text-red-200">{error}</div>}
      {stage === "unlock" && <form onSubmit={unlock} className="space-y-4"><h2 className="text-xl font-semibold">Secure installer access</h2><p className="text-zinc-400">Enter the server-side INSTALL_TOKEN. It is exchanged once for a short-lived, HttpOnly setup session and is never stored in site configuration.</p><label className="block">Installation token<input autoFocus required type="password" value={token} onChange={(e)=>setToken(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3" /></label><button className="rounded-lg bg-red-600 px-5 py-3 font-semibold">Unlock installer</button></form>}
      {stage === "system" && <><h2 className="text-xl font-semibold">System and connection checks</h2><Check ok={initialState.bootstrapReady} label="Installer core migration" detail={initialState.bootstrapReady ? "Core tables and locking RPC are available." : "Run the documented psql bootstrap command first."}/><Check ok label="Server runtime" detail="Next.js server actions are available."/><Check ok={initialState.errorCode !== "SERVER_CONFIGURATION_REQUIRED"} label="Supabase service connection" detail="Service credentials remain on the server."/></>}
      {stage === "site" && <><h2 className="text-xl font-semibold">Site identity and branding</h2><Field label="Website name" value={form.siteName} onChange={(v)=>update("siteName",v)}/><Field label="Description" value={form.description} onChange={(v)=>update("description",v)}/><Field label="Public URL" value={form.publicUrl} onChange={(v)=>update("publicUrl",v)}/><Field label="Logo URL (optional)" value={form.logoUrl} onChange={(v)=>update("logoUrl",v)}/><div className="grid grid-cols-2 gap-4"><Color label="Primary" value={form.primaryColor} onChange={(v)=>update("primaryColor",v)}/><Color label="Accent" value={form.accentColor} onChange={(v)=>update("accentColor",v)}/></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Forum term" value={form.forumTerm} onChange={(v)=>update("forumTerm",v)}/><Field label="Knowledge term" value={form.knowledgeTerm} onChange={(v)=>update("knowledgeTerm",v)}/><Field label="Vendor term" value={form.vendorTerm} onChange={(v)=>update("vendorTerm",v)}/></div></>}
      {stage === "modules" && <><h2 className="text-xl font-semibold">Optional modules</h2><p className="text-zinc-400">Only modules whose database migration has been applied can be selected. Hard dependencies are selected automatically.</p><div className="grid gap-3">{Object.entries(OPTIONAL_MODULES).map(([key,value])=>{ const availability = initialState.modules[key as keyof ModuleAvailability]; return <label key={key} className={`flex gap-3 rounded-lg border p-4 ${availability.available ? "border-zinc-700" : "cursor-not-allowed border-zinc-800 opacity-60"}`}><input type="checkbox" disabled={!availability.available} checked={selected.includes(key as never)} onChange={()=>toggleModule(key)}/><span><b>{value.label}</b>{!availability.available && <strong className="ml-2 text-amber-300">Unavailable</strong>}<small className="block text-zinc-400">{availability.reason}</small></span></label>})}</div></>}
      {stage === "auth" && <><h2 className="text-xl font-semibold">Authentication, storage, and email</h2><Check ok label="Avatar storage" detail="The core migration creates the restricted avatars bucket."/><label className="flex gap-3"><input type="checkbox" checked={form.allowSignup} onChange={(e)=>update("allowSignup",e.target.checked)}/>Allow public registration</label><label className="flex gap-3"><input type="checkbox" checked={form.requireEmailConfirmation} onChange={(e)=>update("requireEmailConfirmation",e.target.checked)}/>Require email confirmation</label><p className="text-sm text-amber-300">Confirm SMTP delivery and Supabase redirect URLs in the Supabase dashboard. The installer saves these policies but cannot safely configure provider secrets.</p></>}
      {stage === "owner" && <><h2 className="text-xl font-semibold">First owner</h2><p className="text-zinc-400">Authorization is written to protected database role tables, never user-editable metadata.</p><Field label="Email" value={form.email} type="email" onChange={(v)=>update("email",v)}/><Field label="Username" value={form.username} onChange={(v)=>update("username",v)}/><Field label="Password (12+ characters)" value={form.password} type="password" onChange={(v)=>update("password",v)}/></>}
      {stage === "review" && <><h2 className="text-xl font-semibold">Review installation</h2><dl className="grid grid-cols-[10rem_1fr] gap-2 rounded-lg bg-zinc-950 p-4"><dt>Site</dt><dd>{form.siteName}</dd><dt>URL</dt><dd>{form.publicUrl}</dd><dt>Owner</dt><dd>{form.email}</dd><dt>Modules</dt><dd>{selected.join(", ") || "Core only"}</dd><dt>Skipped</dt><dd>{Object.keys(OPTIONAL_MODULES).filter(x=>!selected.includes(x as never)).join(", ") || "None"}</dd></dl><p className="text-zinc-400">Finalization uses a database advisory lock. If interrupted, reuse the same owner email to resume safely.</p></>}
      {stage === "installing" && <div className="py-16 text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-zinc-700 border-t-red-500"/><h2 className="mt-5 text-xl font-semibold">Finalizing installation…</h2><p className="text-zinc-400">Creating the owner and atomically locking setup.</p></div>}
      {stage === "success" && <div className="py-12 text-center"><div className="text-5xl">✓</div><h2 className="mt-4 text-2xl font-bold">Installation complete</h2><p className="mt-2 text-zinc-400">The installer is permanently locked. Sign in with the owner account.</p><a href="/auth/login" className="mt-6 inline-block rounded-lg bg-red-600 px-5 py-3 font-semibold">Sign in</a></div>}
      {stages.includes(stage) && stage !== "unlock" && <div className="flex justify-between border-t border-zinc-800 pt-5"><button onClick={back} disabled={stage==="system"} className="rounded-lg border border-zinc-700 px-5 py-3 disabled:opacity-40">Back</button>{stage === "review" ? <button onClick={install} className="rounded-lg bg-red-600 px-5 py-3 font-semibold">Install website</button> : <button onClick={next} disabled={stage === "system" && !initialState.bootstrapReady} className="rounded-lg bg-red-600 px-5 py-3 font-semibold disabled:opacity-40">Continue</button>}</div>}
    </section></div></main>;
}

function Check({ok,label,detail}:{ok:boolean;label:string;detail:string}) { return <div className={`rounded-lg border p-4 ${ok?'border-emerald-800 bg-emerald-950/30':'border-amber-700 bg-amber-950/30'}`}><b>{ok?'✓':'!'} {label}</b><p className="text-sm text-zinc-400">{detail}</p></div> }
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}) { return <label className="block text-sm">{label}<input required type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3"/></label> }
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="block text-sm">{label} color<div className="mt-1 flex gap-2"><input type="color" value={value} onChange={(e)=>onChange(e.target.value)} className="h-12 w-14 rounded bg-transparent"/><input value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3"/></div></label> }
